# -*- coding: utf-8 -*-
"""noelipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VdoVjDaR2KXSAqClybJRSBwW9GpgjdKs
"""

import random
from random import choice  
import numpy as np
from numpy import random as rd

#créer algo pour tirage au sort
#regles: _ on ne peut pas se tirer au sort
#        _ on n'est pas obligé de faire un cadeau à la personne qui nous a tiré au sort
#on doit aussi supprimer le nom tiré

print("Bienvenue au tirage de cadeau de noël,nous allons sélectionner, qui offre un cadeau à qui, budget de 5€ par cadeau, chocolats, câbles USB, petite enceinte....")

print("attention ça va aller très vite!")

lst1 = ['Alexis','Audrey','Clément','Fatima','Grégory','Jonathan','Maria','Martin_B','Martin_C','Reine'] 
lst2 = ['Alexis','Audrey','Clément','Fatima','Grégory','Jonathan','Maria','Martin_B','Martin_C','Reine']                                                                                      
                                                                                                                                                                         
while lst1 and lst2: 
  choice1 = choice(lst1) 
  choice2 = choice(lst2)
  if choice1==choice2:
    choice1 = choice(lst1) 
    choice2 = choice(lst2)
  lst1.remove(choice1) 
  lst2.remove(choice2) 
  print(f'{choice1} offre un cadeau à {choice2}')

"""test avec méthode  stockage


"""

print("pour RAMI chacun prévoit 1 € de plus soit 10€ au Total pour un cadeau spécial en commun pour Rami")